packages:
  - "apps/*"
  - "packages/*"

catalog:
  "@orpc/contract": "^1.1.0"
  "@orpc/openapi": "^1.1.0"
  "@orpc/server": "^1.1.0"
  "@orpc/zod": "^1.1.0"
  eslint: ^9.25.1
  hono: ^4.7.8
  zod: ^3.24.3
